name: Sync R2
on:
  push:
    branches: master
jobs:
  sync-r2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
      AWS_REGION: auto
      AWS_EC2_METADATA_DISABLED: true
      AWS_S3_FORCE_PATH_STYLE: true
      R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync content to R2
        run: |
          aws s3 sync --content-type text/plain --metadata-directive REPLACE . s3://crowdsec-hub-data-prod --exclude ".git/*" --exclude ".github/*" --endpoint-url "$R2_ENDPOINT"
